//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mod.ModMenu.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mod.ModMenu.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable automatic item pickup.
        /// </summary>
        public static string AutoPickUpDescription {
            get {
                return ResourceManager.GetString("AutoPickUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically pick up items.
        /// </summary>
        public static string AutoPickUpTitle {
            get {
                return ResourceManager.GetString("AutoPickUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto up newborn acc to mission to state.
        /// </summary>
        public static string AutoUpSSDescription {
            get {
                return ResourceManager.GetString("AutoUpSSDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto up newborn.
        /// </summary>
        public static string AutoUpSSTitle {
            get {
                return ResourceManager.GetString("AutoUpSSTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically avoid super monsters when slaughtering.
        /// </summary>
        public static string AvoidSMDescription {
            get {
                return ResourceManager.GetString("AvoidSMDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid super monsters when slaughtering.
        /// </summary>
        public static string AvoidSMTitle {
            get {
                return ResourceManager.GetString("AvoidSMTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}!.
        /// </summary>
        public static string BoolToggleStatusMsgTemplate {
            get {
                return ResourceManager.GetString("BoolToggleStatusMsgTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable boss notification display.
        /// </summary>
        public static string BossListDescription {
            get {
                return ResourceManager.GetString("BossListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boss announcement.
        /// </summary>
        public static string BossListTitle {
            get {
                return ResourceManager.GetString("BossListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows approximately the exact time of NRD, shield, monkey, whistle... of the character in focus.
        /// </summary>
        public static string CharInfoDescription {
            get {
                return ResourceManager.GetString("CharInfoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show character information.
        /// </summary>
        public static string CharInfoTitle {
            get {
                return ResourceManager.GetString("CharInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show disciples in the list of characters in the map (disciples without a master in the map are not displayed).
        /// </summary>
        public static string CharListDcpDescription {
            get {
                return ResourceManager.GetString("CharListDcpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show disciples in the list.
        /// </summary>
        public static string CharListDcpTitle {
            get {
                return ResourceManager.GetString("CharListDcpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a list of characters in the map.
        /// </summary>
        public static string CharListDescription {
            get {
                return ResourceManager.GetString("CharListDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show character list.
        /// </summary>
        public static string CharListTitle {
            get {
                return ResourceManager.GetString("CharListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable automatic terrain traversal while slaughtering.
        /// </summary>
        public static string CrossInMassacreDescription {
            get {
                return ResourceManager.GetString("CrossInMassacreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross the terrain while slaughtering.
        /// </summary>
        public static string CrossInMassacreTitle {
            get {
                return ResourceManager.GetString("CrossInMassacreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace game background with custom background (automatically adjusts background to fit screen size).
        /// </summary>
        public static string CustomBgDescription {
            get {
                return ResourceManager.GetString("CustomBgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom background.
        /// </summary>
        public static string CustomBgTitle {
            get {
                return ResourceManager.GetString("CustomBgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the default mouse pointer to a custom mouse pointer.
        /// </summary>
        public static string CustomCursorDescription {
            get {
                return ResourceManager.GetString("CustomCursorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom cursors.
        /// </summary>
        public static string CustomCursorTitle {
            get {
                return ResourceManager.GetString("CustomCursorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable display of custom logo on game screen.
        /// </summary>
        public static string CustomLogoDescription {
            get {
                return ResourceManager.GetString("CustomLogoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom logos.
        /// </summary>
        public static string CustomLogoTitle {
            get {
                return ResourceManager.GetString("CustomLogoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable mob kills counting.
        /// </summary>
        public static string KillCountDescription {
            get {
                return ResourceManager.GetString("KillCountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count mob kills.
        /// </summary>
        public static string KillCountTitle {
            get {
                return ResourceManager.GetString("KillCountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable automatic monster attack.
        /// </summary>
        public static string MassacreDescription {
            get {
                return ResourceManager.GetString("MassacreDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massacre.
        /// </summary>
        public static string MassacreTitle {
            get {
                return ResourceManager.GetString("MassacreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable the limit on the number of times an item can be automatically picked up.
        /// </summary>
        public static string PickUpLimitDescription {
            get {
                return ResourceManager.GetString("PickUpLimitDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit the number of pickups.
        /// </summary>
        public static string PickUpLimitTitle {
            get {
                return ResourceManager.GetString("PickUpLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn on/off automatic attack.
        /// </summary>
        public static string SelfAttackDescription {
            get {
                return ResourceManager.GetString("SelfAttackDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-attack.
        /// </summary>
        public static string SelfAttackTitle {
            get {
                return ResourceManager.GetString("SelfAttackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays people, monsters, bosses... within bomb range.
        /// </summary>
        public static string ShowBomDistanceDescription {
            get {
                return ResourceManager.GetString("ShowBomDistanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show bomb distance.
        /// </summary>
        public static string ShowBomDistanceTitle {
            get {
                return ResourceManager.GetString("ShowBomDistanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/disable filtering to not pick up other people&apos;s items.
        /// </summary>
        public static string SkiptNotOwnedPickUpDescription {
            get {
                return ResourceManager.GetString("SkiptNotOwnedPickUpDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t pick up other people&apos;s things.
        /// </summary>
        public static string SkiptNotOwnedPickUpTitle {
            get {
                return ResourceManager.GetString("SkiptNotOwnedPickUpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn off Vsync if you want to adjust FPS!.
        /// </summary>
        public static string VSyncDescription {
            get {
                return ResourceManager.GetString("VSyncDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VSync.
        /// </summary>
        public static string VSyncTitle {
            get {
                return ResourceManager.GetString("VSyncTitle", resourceCulture);
            }
        }
    }
}
